{% set version = '0.6.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-snowballc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SnowballC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SnowballC/SnowballC_{{ version }}.tar.gz
  sha256: 61617d344444235940f5b9ac1cd6b86938e74a8c76791235724b16b755c3f72c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SnowballC')"           # [not win]
    - "\"%R%\" -e \"library('SnowballC')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://r-forge.r-project.org/projects/r-temis/
  license: BSD_3_clause + file LICENSE
  summary: An R interface to the C 'libstemmer' library that implements Porter's word stemming
    algorithm for collapsing words to a common root to aid comparison of vocabulary.
    Currently supported languages are Danish, Dutch, English, Finnish, French, German,
    Hungarian, Italian, Norwegian, Portuguese, Romanian, Russian, Spanish, Swedish and
    Turkish.
  license_family: BSD

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: SnowballC
# Type: Package
# Version: 0.6.0
# Date: 2019-01-07
# Title: Snowball Stemmers Based on the C 'libstemmer' UTF-8 Library
# Authors@R: person("Milan", "Bouchet-Valat", email="nalimilan@club.fr", role=c("aut", "cre"))
# Description: An R interface to the C 'libstemmer' library that implements Porter's word stemming algorithm for collapsing words to a common root to aid comparison of vocabulary. Currently supported languages are Danish, Dutch, English, Finnish, French, German, Hungarian, Italian, Norwegian, Portuguese, Romanian, Russian, Spanish, Swedish and Turkish.
# License: BSD_3_clause + file LICENSE
# Copyright: Dr Martin Porter (2001) and Richard Boulton (2004, 2005) for the 'libstemmer' C library, and Milan Bouchet-Valat (2013) for the R package contents.
# URL: https://r-forge.r-project.org/projects/r-temis/
# BugReports: https://r-forge.r-project.org/tracker/?group_id=1437
# NeedsCompilation: yes
# Packaged: 2019-01-08 13:36:02 UTC; milan
# Author: Milan Bouchet-Valat [aut, cre]
# Maintainer: Milan Bouchet-Valat <nalimilan@club.fr>
# Repository: CRAN
# Date/Publication: 2019-01-15 16:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
