travis:
  secure:
    BINSTAR_TOKEN: AGPAyg1kHKbxHdlVjcFXdgTWm+VYEeVfqlyUYCdRWM/0vBy3XbpoZeIXvvRfRwOiqsL0wLlS/ZW8l5i2oIxI5t4MUZiRhMkATo0iRP8ZQP5bPzhRDMEdUVs5ShSGmVd2LnfauJ8d/ghbd3/3tmZ1kFOm3gSfqPaU3cVceRiveXMf7URUGLCb9XxSCCbhh6fRFd5hA/DcvGRBhIqw8J0uXX1pZq7v8af6GjcPF98oFT+h/mu0n68ouIc+4i2QawVrn3HXEfkRgtYE7NDA6VHZb4bGDOW7eoyRw2qtnMe+DL0+wJJY/bY39SWo3YF4Zb+g5hpcga3kR1CampeFbsxaFU8s1COtvh+phIrfY68vrTBTVnXkVnU8lr37Uyvd9THlctG/axZVTGPjMEy1VqVLB4SVp9KZS7UdvBHgbliIRJd3o7JEfJ1PjUQ4n2DqYfHPsks2Bp2dSyle1lnCLQhxRJVfFBjZ7+z0R39AZwnMzNcrTqbp3USdC3UJ3uyJb0fH2yiFLHaBQLo89QM719CyOfvZ3fp0qW6NN1r+q45iWbA8XSNhaNSs+VzluhijP2EiyL8sEV1AWU9fsnDx/VqKja54ugisIGdbWnUbswX22yB/KGrw7MbJbZJ5B0tKHY2pRRASJKoPN/PC6QcmxJnLgv4xByTDsBiwZmc2ycBbwFA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
