travis:
  secure:
    BINSTAR_TOKEN: IMjWw4h5a7H0UWRHzQ9RyWAjqZxtaJVOZrPuGEpmp8VfGAgvpn9xMyfBmFkFHwRkrf+WFKaZjsfuRHf1+IZo1eeC2KIi6TzyktPq1x/vooO5mOJvoO/JISdEaq4j7ras4T3yPWR8NA62zTuqMfRuB1a5QUpTnt1V7EGywWvtNiSvjDimolbCTOpQ1O0IfFRfvJASHqMiPrWsdM+Py9pZzp+3GOWSQfuxOhMxhQRpyyk7dQ8pcxwCbQbUuojbJwm9W9zPIyK4oIZ6GBTVXZCe6NdkyYDuBf7P3tDQBqap4mrlo1KU2uczR8jrBtj5T+92v6y9U1Tnvh90XxkaXUDwciC9qW5GrJuS8GjhZB95+vl7BMJT7DgOWDRSZstARg+PLxPk8cD93IzZLmJWUYxpTATOnVhsq9kyCZkOsPMMiwwLHbNUZ9tJPag6mZhSO17WVl7mKQqhPAXklJnd8ABfpQJ/FKHNBMUtDLgYE2mjQhiyRb/Yqw64CLX5vWBMfYh8iCULSFxBay/CWZjqtD8Ug10qrG5EAwijwhoOnA3eedlApJEY5+1ysLAanGAlnLxqo5ftbMGI9de4z+ar87Y3XfaqiXA6OVU/e1ZFmUiMoyTZpJP9zbmGSniAx2TL26IOpiQCgKcpMuq5LW6M3aYHTXKTkAkzn69/4zmBqzAR8mc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
